"""Generate src/telegram_bot_calendar/_locale_data.py from CLDR via Babel.

Run: python scripts/gen_locales.py (needs the ``babel`` dev extra).
Months: stand-alone abbreviated names. Weekdays: stand-alone narrow names, or
stand-alone short names when narrow ones are empty or only digits. en, eo and ru
are fixed by hand and never change.
Labels: CLDR ``yMMM``, ``y``, ``MMMd`` and ``yMMMd`` patterns become templates with
``{year}``, ``{month}`` and ``{day}``; ``{month}`` is the abbreviated name above. A
pattern with a numeric-only month falls back to the month name in a plain order.
"""

from __future__ import annotations

from pathlib import Path
from typing import cast

from babel import Locale, localedata
from babel.dates import get_day_names, get_month_names, tokenize_pattern

OUT = Path(__file__).resolve().parent.parent / "src" / "telegram_bot_calendar" / "_locale_data.py"

FIXED: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "en": (("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"), tuple("MTWTFSS")),
    "eo": (("jan", "feb", "mar", "apr", "maj", "jun", "jul", "aŭg", "sep", "okt", "nov", "dec"), tuple("LMMĴVSD")),
    "ru": (
        ("янв", "фев", "мар", "апр", "май", "июн", "июл", "авг", "сен", "окт", "ноя", "дек"),
        ("П", "В", "С", "Ч", "П", "С", "В"),
    ),
}
FIXED_LABELS = ("{month} {year}", "{year}", "{day} {month}", "{day} {month} {year}")
SKELETONS = ("yMMM", "y", "MMMd", "yMMMd")
FIELDS = {"y": "{year}", "d": "{day}"}

CODES = (
    "ar",
    "az",
    "bg",
    "bn",
    "ca",
    "cs",
    "da",
    "de",
    "el",
    "es",
    "et",
    "fa",
    "fi",
    "fil",
    "fr",
    "he",
    "hi",
    "hr",
    "hu",
    "id",
    "it",
    "ja",
    "ka",
    "kk",
    "ko",
    "lt",
    "lv",
    "ms",
    "nb",
    "nl",
    "pl",
    "pt",
    "pt_BR",
    "ro",
    "sk",
    "sl",
    "sr",
    "sv",
    "sw",
    "ta",
    "th",
    "tr",
    "uk",
    "ur",
    "uz",
    "vi",
    "zh_Hans",
    "zh_Hant",
)


def names(code: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    if code in FIXED:
        return FIXED[code]
    # Babel resolves stand-alone aliases in place inside its shared cache, so one
    # locale's names can leak into the next one. Start each locale with a cold cache.
    localedata._cache.clear()
    abbr = get_month_names("abbreviated", "stand-alone", code)
    months = tuple(str(abbr[m]).strip() for m in range(1, 13))
    days = [str(get_day_names("narrow", "stand-alone", code)[d]).strip() for d in range(7)]
    if not all(days) or all(name.isdigit() for name in days):  # digits would look like dates
        days = [str(get_day_names("short", "stand-alone", code)[d]).strip() for d in range(7)]
    return months, tuple(days)


def _template(pattern: str, month_suffix: str) -> str | None:
    """``pattern`` as a template, or None when it shows the month only as a number."""
    out: list[str] = []
    tokens = tokenize_pattern(pattern)
    for i, (kind, value) in enumerate(tokens):
        if kind == "chars":
            out.append(str(value))
            continue
        field, count = cast("tuple[str, int]", value)
        if field in FIELDS:
            out.append(FIELDS[field])
        elif field in "ML" and count >= 3:
            out.append("{month}")
        elif field in "ML" and month_suffix and i + 1 < len(tokens) and str(tokens[i + 1][1]).startswith(month_suffix):
            # The name already carries the suffix, e.g. "5月"; drop it from the next literal.
            out.append("{month}")
            kind2, text = tokens[i + 1]
            tokens[i + 1] = (kind2, str(text)[len(month_suffix) :])
        else:
            return None
    return "".join(out)


def labels(code: str) -> tuple[str, ...]:
    if code in FIXED:
        return FIXED_LABELS
    localedata._cache.clear()
    skeletons = Locale.parse(code).datetime_skeletons
    months = names(code)[0]
    suffix = months[4].lstrip("0123456789")  # "月" in "5月", "" for word names
    out = []
    for skeleton, fallback in zip(SKELETONS, FIXED_LABELS):
        template = _template(str(skeletons[skeleton]), suffix)
        out.append(fallback if template is None else template)
    return tuple(out)


def _label_table(name: str, index: int, codes: list[str]) -> list[str]:
    lines = [f"{name}: dict[str, str] = {{"]
    lines += [f'    "{code}": "{labels(code)[index]}",' for code in codes]
    lines.append("}")
    return lines


def _table(name: str, index: int, codes: list[str]) -> list[str]:
    lines = [f"{name}: dict[str, tuple[str, ...]] = {{"]
    for code in codes:
        items = ", ".join(f'"{n}"' for n in names(code)[index])
        lines.append(f'    "{code}": ({items}),')
    lines.append("}")
    return lines


def render() -> str:
    codes = sorted([*FIXED, *CODES])
    head = [
        '"""Names and label templates per locale. Generated by scripts/gen_locales.py; do not edit."""',
        "",
        "# ruff: noqa: E501, RUF001",
        "from __future__ import annotations",
        "",
    ]
    body = [*_table("MONTH_NAMES", 0, codes), "", *_table("WEEKDAY_NAMES", 1, codes)]
    for i, name in enumerate(("MONTH_YEAR", "YEAR", "DAY_MONTH", "DAY_MONTH_YEAR")):
        body += ["", *_label_table(name, i, codes)]
    return "\n".join([*head, *body]) + "\n"


def main() -> None:
    OUT.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
