"""Generate src/telegram_bot_calendar/_locale_data.py from CLDR via Babel.

Run: python scripts/gen_locales.py (needs the ``babel`` dev extra).
Months: stand-alone abbreviated names. Weekdays: stand-alone narrow names, or
stand-alone short names when narrow ones are empty or only digits. en, eo and ru
are fixed by hand and never change.
"""

from __future__ import annotations

from pathlib import Path

from babel import localedata
from babel.dates import get_day_names, get_month_names

OUT = Path(__file__).resolve().parent.parent / "src" / "telegram_bot_calendar" / "_locale_data.py"

FIXED: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "en": (("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"), tuple("MTWTFSS")),
    "eo": (("jan", "feb", "mar", "apr", "maj", "jun", "jul", "aŭg", "sep", "okt", "nov", "dec"), tuple("LMMĴVSD")),
    "ru": (
        ("янв", "фев", "мар", "апр", "май", "июн", "июл", "авг", "сен", "окт", "ноя", "дек"),
        ("П", "В", "С", "Ч", "П", "С", "В"),
    ),
}
CODES = (
    "ar",
    "az",
    "bg",
    "bn",
    "ca",
    "cs",
    "da",
    "de",
    "el",
    "es",
    "et",
    "fa",
    "fi",
    "fil",
    "fr",
    "he",
    "hi",
    "hr",
    "hu",
    "id",
    "it",
    "ja",
    "ka",
    "kk",
    "ko",
    "lt",
    "lv",
    "ms",
    "nb",
    "nl",
    "pl",
    "pt",
    "pt_BR",
    "ro",
    "sk",
    "sl",
    "sr",
    "sv",
    "sw",
    "ta",
    "th",
    "tr",
    "uk",
    "ur",
    "uz",
    "vi",
    "zh_Hans",
    "zh_Hant",
)


def names(code: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    if code in FIXED:
        return FIXED[code]
    # Babel resolves stand-alone aliases in place inside its shared cache, so one
    # locale's names can leak into the next one. Start each locale with a cold cache.
    localedata._cache.clear()
    abbr = get_month_names("abbreviated", "stand-alone", code)
    months = tuple(str(abbr[m]).strip() for m in range(1, 13))
    days = [str(get_day_names("narrow", "stand-alone", code)[d]).strip() for d in range(7)]
    if not all(days) or all(name.isdigit() for name in days):  # digits would look like dates
        days = [str(get_day_names("short", "stand-alone", code)[d]).strip() for d in range(7)]
    return months, tuple(days)


def _table(name: str, index: int, codes: list[str]) -> list[str]:
    lines = [f"{name}: dict[str, tuple[str, ...]] = {{"]
    for code in codes:
        items = ", ".join(f'"{n}"' for n in names(code)[index])
        lines.append(f'    "{code}": ({items}),')
    lines.append("}")
    return lines


def render() -> str:
    codes = sorted([*FIXED, *CODES])
    head = [
        '"""Month and weekday names per locale. Generated by scripts/gen_locales.py; do not edit."""',
        "",
        "# ruff: noqa: E501, RUF001",
        "from __future__ import annotations",
        "",
    ]
    body = [*_table("MONTH_NAMES", 0, codes), "", *_table("WEEKDAY_NAMES", 1, codes)]
    return "\n".join([*head, *body]) + "\n"


def main() -> None:
    OUT.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
